version: '3.4'

services:
  projectanimesapi:
    container_name: api
    build:
      context: .
      dockerfile: ProjectAnimesAPI/Dockerfile
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ./ProjectAnimesAPI:/src
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_01
    ports:
      - "1433:1433"
    volumes:
      - ./Docker/db/mssql/data:/var/opt/mssql/data